In [2]:
import numpy as np

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[2]

2

In [8]:
x[-2]

8

In [10]:
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
x[1,3]

8

In [13]:
x[1,-1] 

9

In [14]:
x[0]

array([0, 1, 2, 3, 4])

In [20]:
x[:,1]

array([1, 6])

In [21]:
x[:,1:2]

array([[1],
       [6]])

In [22]:
x[:,1:3]

array([[1, 2],
       [6, 7]])

In [23]:
# x[0] returns a reference to the sub array in x and therefore
# x[0][1] also works, but this is less efficient than x[0,1] as in
# the former a new temporary array is created

In [25]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x[2:5]

array([2, 3, 4])

In [27]:
x[:-7]

array([0, 1, 2])

In [31]:
x[1:7:2]

array([1, 3, 5])

In [9]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [34]:
y[1:5:2, ::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [4]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [5]:
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [8]:
# When index arrays are used, the same shape of the index array is returned.
x[np.array([[1,1],[2,3]])]

array([[9, 9],
       [8, 7]])

In [10]:
# 1st array corresponds to row indexes, 2nd array corresponds to column indexes

# if the index arrays do not have the same shape, there is an attempt to 
# broadcast them to the same shape
y[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [11]:
# broadcasting mechanism allows index arrays to be combined with scalars for other 
# indices.
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

In [12]:
# possible to partially index an array with index arrays.
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [16]:
b = y>20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [17]:
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [18]:
b[:,5]

array([False, False, False,  True,  True])

In [19]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [21]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [23]:
b = np.array([[True, True, False], [False, True, True]])
b

array([[ True,  True, False],
       [False,  True,  True]])

In [24]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])